baseURL = 'https://icya.pages.dev/'
languageCode = 'en-us'
title = 'Icy'
theme = 'hugo-coder'

[params]
author = "Icy"
description = "An ambitious attempt"
info = ["Fantastic Fantasist", "Student"]
avatarURL = "images/miku.webp"
faviconsvg = "favicon.svg"
colorScheme = "dark"
hideColorSchemeToggle = "true"
since = 2025

[[params.social]]
name = "GitHub"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/Icyvert"
target = "_blank"

[[params.social]]
name = "Monkeytype"
icon = "fa-solid fa-keyboard fa-2x"
weight = 2
url = "https://monkeytype.com/profile/Icya"
target = "_blank"

[[params.social]]
name = "MyAnimeList"
icon = "fa-solid fa-book-bookmark fa-2x"
weight = 3
url = "https://myanimelist.net/profile/Icya"
target = "_blank"

[[params.social]]
name = "Reddit"
icon = "fa-brands fa-reddit fa-2x"
weight = 4
url = "https://www.reddit.com/user/Icy687"
target = "_blank"

[[params.social]]
name = "Twitter"
icon = "fa-brands fa-x-twitter fa-2x"
weight = 5
url = "https://x.com/Icyvertt"
target = "_blank"

[[menu.main]]
name = "Contact"
weight = 1
url = "contact"

[[menu.main]]
name = "Resources"
weight = 2
url = "resources"
